---
title: "Les jeux olympiques : OlympicsWeather"
author: "Cassandre Orhan"
date: "2024-03-09"
---

Ce package contient un ensemble de fonction permetant d'obtenir en temps réel les prévisions météo des sites olympiques en vu des JO.

Afin de realiser ce package nous avons utiliser la librairie `usethis`, il n'est pas nécessaire d'installer explicitement cette librairie car elle fait partie des librairies qui sont automatiquement installées lors de l'installation de R.

Les exemples inclus dans ce package pour illustrer les fonctions correspondent au site olympique "Parc des princes" à Paris avec comme coordonnée géographique (48.841319, 2.253076)

## Perform_request

Ce code définit une fonction interne appelée `perform_request`, conçue pour récupérer des données brutes de prévisions météorologiques à partir d'une API en fournissant les coordonnées GPS d'un emplacement spécifique. La fonction utilise les coordonnées de latitude et de longitude pour effectuer une requête vers une URL API définie précédemment. Elle demande des données spécifiques telles que la température, la probabilité de précipitations, etc., sur une base horaire. Les données récupérées sont ensuite formatées et retournées sous forme de tibble, une structure de données de type tableau, pour une utilisation ultérieure. Des exemples d'utilisation sont inclus pour guider les utilisateurs sur la manière d'appeler cette fonction avec les bonnes coordonnées.

L'exemple inclus retourne une tibble contenant les prévisions météorologiques pour les coordonnées géographiques spécifiées

## Unnest_response

Ce code définit une fonction interne nommée `unnest_response`, qui prend les données brutes de prévisions météo en entrée et les transforme en un format plus lisible. Les données brutes, obtenues avec la fonction `perform_request,`sont structurées sous forme de listes imbriquées. Cette fonction extrait les informations pertinentes telles que la date et l'heure, la température, la température ressentie, la probabilité de précipitation et la quantité de précipitation, puis les organise dans un tibble facilement exploitable.

L'exemple inclus retourne une tibble contenant les prévisions météorologiques pour les coordonnées géographiques spécifiées mais dans un format plus clair et lisible.

## get_weather_forecast

Cette fonction, intitulée "Prévision météo des sites olympiques", permet de récupérer une table de prévisions météorologiques pour une coordonnée GPS donnée ou une adresse. Les prévisions incluent des informations telles que la température, la probabilité de précipitations, etc. Elle peut être utilisée en spécifiant soit les coordonnées GPS sous forme d'un vecteur numérique, soit une adresse en tant que chaîne de caractères. La fonction fait appel à des fonctions internes pour convertir les adresses en coordonnées GPS et pour obtenir les prévisions météorologiques à partir de ces coordonnées. Elle retourne ensuite un tibble contenant les prévisions météo formatées.

## visualize_weather_forecast

Cette fonction, prend en entrée les résultats obtenus à partir de la fonction get_forecast et produit une sortie visuelle avec deux pages de représentation graphique, une page pour les graphiques sur les températures, donc température et température ressentie et une autres pages concernant les précipitations et les probabilités de précipitations.Les graphiques sont générés à partir des données de prévisions météorologiques pour un emplacement spécifié.
